service: product-search

frameworkVersion: '3'

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1

functions:
  searchProduct:
    handler: handler.search
    events:
      - httpApi:
          path: /search
          method: post

package:
  patterns:
    - handler.mjs
    - package.json
    - node_modules/**
    - .env